-- QUESTION # 1

CREATE TABLE ZONG_DATABASE (
PACKAGE_ID NUMBER,
TITLE VARCHAR(20),
RATE NUMBER,
PRIMARY KEY (PACKAGE_ID)
);

CREATE TABLE PACKAGES_HISTORY (
ID NUMBER,
TITLE varchar(20),
RATE NUMBER,
RECORD_DATE date,
PRIMARY KEY (ID)
);


CREATE OR REPLACE TRIGGER PACKAGE_CHANGE_TRIGGER
BEFORE UPDATE OR DELETE
ON ZONG_DATABASE
FOR EACH ROW
BEGIN
INSERT INTO PACKAGES_HISTORY VALUES(:OLD.PACKAGE_ID, :OLD.TITLE, :OLD.RATE, SYSDATE);
END;
/


-- QUESTION # 2

CREATE TABLE T (
id INT NOT NULL PRIMARY KEY,
S VARCHAR(40)
);
`
SELECT * from T;

INSERT INTO T VALUES (1, 'Hassan');
INSERT INTO T VALUES (2, 'Tashik');
INSERT INTO T VALUES (3, 'Sajjad');
INSERT INTO T VALUES (4, 'Unais');
INSERT INTO T VALUES (5, 'Mustafa');

SELECT * FROM T ;

ROLLBACK;
SELECT * FROM T ;
COMMIT;

ROLLBACK;
SELECT * FROM T ;



